name: Run Hello_world python
on: push
jobs:
  hello:
    runs-on: ubuntu-latest

    steps:
    - name: clone-repo
      uses: actions/checkout@v4

    - name: python-setup
      uses: actions/checkout@v4
      with:
        python-version: '3.10' 

    - name: Run-python
      run: python hellow.py

    
